/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:8dfb0929-9b4d-4dc1-ad59-a5b4dc933392",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_NDmpe8id7",
    "aws_user_pools_web_client_id": "77pj8di6655gqss7o8rl7j0v2d",
    "oauth": {}
};


export default awsmobile;
